completed prep-css-flexbox exercise.
Jianhuang8/prep-0721-code-solutions pull request #9
Opened 2021-08-06 05:21 UTC by Jianhuang8

![Screenshot 2021-08-05 221607](https://user-images.githubusercontent.com/88024508/128459980-7cdeb020-22ed-4d4c-b523-b8ac1b23a1cd.png)
![Screenshot 2021-08-05 221607](https://user-images.githubusercontent.com/88024508/128459981-e0fea6c5-22d0-4dc5-bc80-904707122e92.png)
![Screenshot 2021-08-05 221627](https://user-images.githubusercontent.com/88024508/128459983-e10d70a5-b5ac-4db1-8d57-01001f7188fa.png)
![Screenshot 2021-08-05 221638](https://user-images.githubusercontent.com/88024508/128459990-dd3f51c4-f923-4f9e-968a-b5e1822783a4.png)

2021-08-06 14:44 UTC, thebearingedge requested changes

2021-08-06 14:44 UTC, thebearingedge commented on prep-css-flexbox/justify-content.html
> +  flex-basis: 25%;
Hi Jayden, the `flex-basis` property should be used on "flex items", that is, elements who are children of an element who has `display: flex`. So you want to move your `flex-basis` to the `.card-container` rule-set.

2021-08-07 06:46 UTC, Jianhuang8 commented
i just fixed the mistake. thank you tim

2021-08-07 15:21 UTC, thebearingedge approved these changes

2021-08-07 17:07 UTC, merged